//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFI.Attachment {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://127.0.0.1/", ConfigurationName="Attachment.wsAttachmentSoap")]
    public interface wsAttachmentSoap {
        
        // CODEGEN: Generating message contract since message part namespace (http://127.0.0.1//getDocAttachment/Response) does not match the default value (http://127.0.0.1/)
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1/getDocAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="document")]
        FFI.Attachment.getDocAttachmentResponse1 getDocAttachment(FFI.Attachment.getDocAttachmentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1/getDocAttachment", ReplyAction="*")]
        System.Threading.Tasks.Task<FFI.Attachment.getDocAttachmentResponse1> getDocAttachmentAsync(FFI.Attachment.getDocAttachmentRequest1 request);
        
        // CODEGEN: Generating message contract since message part namespace (http://127.0.0.1//saveDocAttachment/Response) does not match the default value (http://127.0.0.1/)
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1/saveDocAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="document")]
        FFI.Attachment.saveDocAttachmentResponse1 saveDocAttachment(FFI.Attachment.saveDocAttachmentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1/saveDocAttachment", ReplyAction="*")]
        System.Threading.Tasks.Task<FFI.Attachment.saveDocAttachmentResponse1> saveDocAttachmentAsync(FFI.Attachment.saveDocAttachmentRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//getDocAttachment/Request")]
    public partial class getDocAttachmentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getDocAttachmentRequestcontext contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getDocAttachmentRequestcontext context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//getDocAttachment/Request")]
    public partial class getDocAttachmentRequestcontext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIdField;
        
        private string userIdField;
        
        private string dbServerField;
        
        private string dbNameField;
        
        private string dbUserField;
        
        private string dbPwdField;
        
        private string orgnIdField;
        
        private string locnIdField;
        
        private getDocAttachmentRequestHeader headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dbServer {
            get {
                return this.dbServerField;
            }
            set {
                this.dbServerField = value;
                this.RaisePropertyChanged("dbServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dbName {
            get {
                return this.dbNameField;
            }
            set {
                this.dbNameField = value;
                this.RaisePropertyChanged("dbName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dbUser {
            get {
                return this.dbUserField;
            }
            set {
                this.dbUserField = value;
                this.RaisePropertyChanged("dbUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string dbPwd {
            get {
                return this.dbPwdField;
            }
            set {
                this.dbPwdField = value;
                this.RaisePropertyChanged("dbPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string orgnId {
            get {
                return this.orgnIdField;
            }
            set {
                this.orgnIdField = value;
                this.RaisePropertyChanged("orgnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string locnId {
            get {
                return this.locnIdField;
            }
            set {
                this.locnIdField = value;
                this.RaisePropertyChanged("locnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public getDocAttachmentRequestHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//getDocAttachment/Request")]
    public partial class getDocAttachmentRequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string menu_idField;
        
        private string doc_numberField;
        
        private System.Nullable<int> doc_rowidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string menu_id {
            get {
                return this.menu_idField;
            }
            set {
                this.menu_idField = value;
                this.RaisePropertyChanged("menu_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string doc_number {
            get {
                return this.doc_numberField;
            }
            set {
                this.doc_numberField = value;
                this.RaisePropertyChanged("doc_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> doc_rowid {
            get {
                return this.doc_rowidField;
            }
            set {
                this.doc_rowidField = value;
                this.RaisePropertyChanged("doc_rowid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Response")]
    public partial class saveDocAttachmentResponseApplicationException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorNumberField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("errorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Response")]
    public partial class saveDocAttachmentResponseUADSApplicationExceptionClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorNumberField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("errorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Response")]
    public partial class saveDocAttachmentResponsecontext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIdField;
        
        private string userIdField;
        
        private string dbServerField;
        
        private string dbNameField;
        
        private string dbUserField;
        
        private string dbPwdField;
        
        private string orgnIdField;
        
        private string locnIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dbServer {
            get {
                return this.dbServerField;
            }
            set {
                this.dbServerField = value;
                this.RaisePropertyChanged("dbServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dbName {
            get {
                return this.dbNameField;
            }
            set {
                this.dbNameField = value;
                this.RaisePropertyChanged("dbName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dbUser {
            get {
                return this.dbUserField;
            }
            set {
                this.dbUserField = value;
                this.RaisePropertyChanged("dbUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string dbPwd {
            get {
                return this.dbPwdField;
            }
            set {
                this.dbPwdField = value;
                this.RaisePropertyChanged("dbPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string orgnId {
            get {
                return this.orgnIdField;
            }
            set {
                this.orgnIdField = value;
                this.RaisePropertyChanged("orgnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string locnId {
            get {
                return this.locnIdField;
            }
            set {
                this.locnIdField = value;
                this.RaisePropertyChanged("locnId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Response")]
    public partial class saveDocAttachmentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private saveDocAttachmentResponsecontext contextField;
        
        private saveDocAttachmentResponseUADSApplicationExceptionClass uADSApplicationExceptionClassField;
        
        private saveDocAttachmentResponseApplicationException applicationExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public saveDocAttachmentResponsecontext context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public saveDocAttachmentResponseUADSApplicationExceptionClass UADSApplicationExceptionClass {
            get {
                return this.uADSApplicationExceptionClassField;
            }
            set {
                this.uADSApplicationExceptionClassField = value;
                this.RaisePropertyChanged("UADSApplicationExceptionClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public saveDocAttachmentResponseApplicationException ApplicationException {
            get {
                return this.applicationExceptionField;
            }
            set {
                this.applicationExceptionField = value;
                this.RaisePropertyChanged("ApplicationException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Request")]
    public partial class saveDocAttachmentRequestList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> attach_rowidField;
        
        private string filenameField;
        
        private string file_versionField;
        
        private string attach_group_codeField;
        
        private string attach_subgroup_codeField;
        
        private string notesField;
        
        private string file_sizeField;
        
        private string file_pathField;
        
        private string mode_flagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> attach_rowid {
            get {
                return this.attach_rowidField;
            }
            set {
                this.attach_rowidField = value;
                this.RaisePropertyChanged("attach_rowid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string file_version {
            get {
                return this.file_versionField;
            }
            set {
                this.file_versionField = value;
                this.RaisePropertyChanged("file_version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string attach_group_code {
            get {
                return this.attach_group_codeField;
            }
            set {
                this.attach_group_codeField = value;
                this.RaisePropertyChanged("attach_group_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string attach_subgroup_code {
            get {
                return this.attach_subgroup_codeField;
            }
            set {
                this.attach_subgroup_codeField = value;
                this.RaisePropertyChanged("attach_subgroup_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string file_size {
            get {
                return this.file_sizeField;
            }
            set {
                this.file_sizeField = value;
                this.RaisePropertyChanged("file_size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string file_path {
            get {
                return this.file_pathField;
            }
            set {
                this.file_pathField = value;
                this.RaisePropertyChanged("file_path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string mode_flag {
            get {
                return this.mode_flagField;
            }
            set {
                this.mode_flagField = value;
                this.RaisePropertyChanged("mode_flag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Request")]
    public partial class saveDocAttachmentRequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string menu_idField;
        
        private string doc_numberField;
        
        private System.Nullable<int> doc_rowidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string menu_id {
            get {
                return this.menu_idField;
            }
            set {
                this.menu_idField = value;
                this.RaisePropertyChanged("menu_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string doc_number {
            get {
                return this.doc_numberField;
            }
            set {
                this.doc_numberField = value;
                this.RaisePropertyChanged("doc_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> doc_rowid {
            get {
                return this.doc_rowidField;
            }
            set {
                this.doc_rowidField = value;
                this.RaisePropertyChanged("doc_rowid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Request")]
    public partial class saveDocAttachmentRequestcontext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIdField;
        
        private string userIdField;
        
        private string dbServerField;
        
        private string dbNameField;
        
        private string dbUserField;
        
        private string dbPwdField;
        
        private string orgnIdField;
        
        private string locnIdField;
        
        private saveDocAttachmentRequestHeader headerField;
        
        private saveDocAttachmentRequestList[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dbServer {
            get {
                return this.dbServerField;
            }
            set {
                this.dbServerField = value;
                this.RaisePropertyChanged("dbServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dbName {
            get {
                return this.dbNameField;
            }
            set {
                this.dbNameField = value;
                this.RaisePropertyChanged("dbName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dbUser {
            get {
                return this.dbUserField;
            }
            set {
                this.dbUserField = value;
                this.RaisePropertyChanged("dbUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string dbPwd {
            get {
                return this.dbPwdField;
            }
            set {
                this.dbPwdField = value;
                this.RaisePropertyChanged("dbPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string orgnId {
            get {
                return this.orgnIdField;
            }
            set {
                this.orgnIdField = value;
                this.RaisePropertyChanged("orgnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string locnId {
            get {
                return this.locnIdField;
            }
            set {
                this.locnIdField = value;
                this.RaisePropertyChanged("locnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public saveDocAttachmentRequestHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("List", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public saveDocAttachmentRequestList[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("List");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Request")]
    public partial class saveDocAttachmentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private saveDocAttachmentRequestcontext contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public saveDocAttachmentRequestcontext context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//getDocAttachment/Response")]
    public partial class getDocAttachmentResponseApplicationException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorNumberField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("errorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//getDocAttachment/Response")]
    public partial class getDocAttachmentResponseUADSApplicationExceptionClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorNumberField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("errorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//getDocAttachment/Response")]
    public partial class getDocAttachmentResponseList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> attach_rowidField;
        
        private string filenameField;
        
        private string file_versionField;
        
        private string attach_group_codeField;
        
        private string attach_groupField;
        
        private string attach_subgroup_codeField;
        
        private string attach_subgroupField;
        
        private string notesField;
        
        private string file_sizeField;
        
        private string file_pathField;
        
        private string mode_flagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> attach_rowid {
            get {
                return this.attach_rowidField;
            }
            set {
                this.attach_rowidField = value;
                this.RaisePropertyChanged("attach_rowid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string file_version {
            get {
                return this.file_versionField;
            }
            set {
                this.file_versionField = value;
                this.RaisePropertyChanged("file_version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string attach_group_code {
            get {
                return this.attach_group_codeField;
            }
            set {
                this.attach_group_codeField = value;
                this.RaisePropertyChanged("attach_group_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string attach_group {
            get {
                return this.attach_groupField;
            }
            set {
                this.attach_groupField = value;
                this.RaisePropertyChanged("attach_group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string attach_subgroup_code {
            get {
                return this.attach_subgroup_codeField;
            }
            set {
                this.attach_subgroup_codeField = value;
                this.RaisePropertyChanged("attach_subgroup_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string attach_subgroup {
            get {
                return this.attach_subgroupField;
            }
            set {
                this.attach_subgroupField = value;
                this.RaisePropertyChanged("attach_subgroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string file_size {
            get {
                return this.file_sizeField;
            }
            set {
                this.file_sizeField = value;
                this.RaisePropertyChanged("file_size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string file_path {
            get {
                return this.file_pathField;
            }
            set {
                this.file_pathField = value;
                this.RaisePropertyChanged("file_path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string mode_flag {
            get {
                return this.mode_flagField;
            }
            set {
                this.mode_flagField = value;
                this.RaisePropertyChanged("mode_flag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//getDocAttachment/Response")]
    public partial class getDocAttachmentResponsecontext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIdField;
        
        private string userIdField;
        
        private string dbServerField;
        
        private string dbNameField;
        
        private string dbUserField;
        
        private string dbPwdField;
        
        private string orgnIdField;
        
        private string locnIdField;
        
        private getDocAttachmentResponseList[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dbServer {
            get {
                return this.dbServerField;
            }
            set {
                this.dbServerField = value;
                this.RaisePropertyChanged("dbServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dbName {
            get {
                return this.dbNameField;
            }
            set {
                this.dbNameField = value;
                this.RaisePropertyChanged("dbName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dbUser {
            get {
                return this.dbUserField;
            }
            set {
                this.dbUserField = value;
                this.RaisePropertyChanged("dbUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string dbPwd {
            get {
                return this.dbPwdField;
            }
            set {
                this.dbPwdField = value;
                this.RaisePropertyChanged("dbPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string orgnId {
            get {
                return this.orgnIdField;
            }
            set {
                this.orgnIdField = value;
                this.RaisePropertyChanged("orgnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string locnId {
            get {
                return this.locnIdField;
            }
            set {
                this.locnIdField = value;
                this.RaisePropertyChanged("locnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("List", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public getDocAttachmentResponseList[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("List");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1//getDocAttachment/Response")]
    public partial class getDocAttachmentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getDocAttachmentResponsecontext contextField;
        
        private getDocAttachmentResponseUADSApplicationExceptionClass uADSApplicationExceptionClassField;
        
        private getDocAttachmentResponseApplicationException applicationExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getDocAttachmentResponsecontext context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public getDocAttachmentResponseUADSApplicationExceptionClass UADSApplicationExceptionClass {
            get {
                return this.uADSApplicationExceptionClassField;
            }
            set {
                this.uADSApplicationExceptionClassField = value;
                this.RaisePropertyChanged("UADSApplicationExceptionClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public getDocAttachmentResponseApplicationException ApplicationException {
            get {
                return this.applicationExceptionField;
            }
            set {
                this.applicationExceptionField = value;
                this.RaisePropertyChanged("ApplicationException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocAttachment", WrapperNamespace="http://127.0.0.1/", IsWrapped=true)]
    public partial class getDocAttachmentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1//getDocAttachment/Request", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://127.0.0.1//getDocAttachment/Request")]
        public FFI.Attachment.getDocAttachmentRequest document;
        
        public getDocAttachmentRequest1() {
        }
        
        public getDocAttachmentRequest1(FFI.Attachment.getDocAttachmentRequest document) {
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocAttachmentResponse", WrapperNamespace="http://127.0.0.1/", IsWrapped=true)]
    public partial class getDocAttachmentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1//getDocAttachment/Response", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://127.0.0.1//getDocAttachment/Response")]
        public FFI.Attachment.getDocAttachmentResponse document;
        
        public getDocAttachmentResponse1() {
        }
        
        public getDocAttachmentResponse1(FFI.Attachment.getDocAttachmentResponse document) {
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveDocAttachment", WrapperNamespace="http://127.0.0.1/", IsWrapped=true)]
    public partial class saveDocAttachmentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Request", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Request")]
        public FFI.Attachment.saveDocAttachmentRequest document;
        
        public saveDocAttachmentRequest1() {
        }
        
        public saveDocAttachmentRequest1(FFI.Attachment.saveDocAttachmentRequest document) {
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveDocAttachmentResponse", WrapperNamespace="http://127.0.0.1/", IsWrapped=true)]
    public partial class saveDocAttachmentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Response", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://127.0.0.1//saveDocAttachment/Response")]
        public FFI.Attachment.saveDocAttachmentResponse document;
        
        public saveDocAttachmentResponse1() {
        }
        
        public saveDocAttachmentResponse1(FFI.Attachment.saveDocAttachmentResponse document) {
            this.document = document;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAttachmentSoapChannel : FFI.Attachment.wsAttachmentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAttachmentSoapClient : System.ServiceModel.ClientBase<FFI.Attachment.wsAttachmentSoap>, FFI.Attachment.wsAttachmentSoap {
        
        public wsAttachmentSoapClient() {
        }
        
        public wsAttachmentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAttachmentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAttachmentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAttachmentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FFI.Attachment.getDocAttachmentResponse1 FFI.Attachment.wsAttachmentSoap.getDocAttachment(FFI.Attachment.getDocAttachmentRequest1 request) {
            return base.Channel.getDocAttachment(request);
        }
        
        public FFI.Attachment.getDocAttachmentResponse getDocAttachment(FFI.Attachment.getDocAttachmentRequest document) {
            FFI.Attachment.getDocAttachmentRequest1 inValue = new FFI.Attachment.getDocAttachmentRequest1();
            inValue.document = document;
            FFI.Attachment.getDocAttachmentResponse1 retVal = ((FFI.Attachment.wsAttachmentSoap)(this)).getDocAttachment(inValue);
            return retVal.document;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FFI.Attachment.getDocAttachmentResponse1> FFI.Attachment.wsAttachmentSoap.getDocAttachmentAsync(FFI.Attachment.getDocAttachmentRequest1 request) {
            return base.Channel.getDocAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FFI.Attachment.getDocAttachmentResponse1> getDocAttachmentAsync(FFI.Attachment.getDocAttachmentRequest document) {
            FFI.Attachment.getDocAttachmentRequest1 inValue = new FFI.Attachment.getDocAttachmentRequest1();
            inValue.document = document;
            return ((FFI.Attachment.wsAttachmentSoap)(this)).getDocAttachmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FFI.Attachment.saveDocAttachmentResponse1 FFI.Attachment.wsAttachmentSoap.saveDocAttachment(FFI.Attachment.saveDocAttachmentRequest1 request) {
            return base.Channel.saveDocAttachment(request);
        }
        
        public FFI.Attachment.saveDocAttachmentResponse saveDocAttachment(FFI.Attachment.saveDocAttachmentRequest document) {
            FFI.Attachment.saveDocAttachmentRequest1 inValue = new FFI.Attachment.saveDocAttachmentRequest1();
            inValue.document = document;
            FFI.Attachment.saveDocAttachmentResponse1 retVal = ((FFI.Attachment.wsAttachmentSoap)(this)).saveDocAttachment(inValue);
            return retVal.document;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FFI.Attachment.saveDocAttachmentResponse1> FFI.Attachment.wsAttachmentSoap.saveDocAttachmentAsync(FFI.Attachment.saveDocAttachmentRequest1 request) {
            return base.Channel.saveDocAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FFI.Attachment.saveDocAttachmentResponse1> saveDocAttachmentAsync(FFI.Attachment.saveDocAttachmentRequest document) {
            FFI.Attachment.saveDocAttachmentRequest1 inValue = new FFI.Attachment.saveDocAttachmentRequest1();
            inValue.document = document;
            return ((FFI.Attachment.wsAttachmentSoap)(this)).saveDocAttachmentAsync(inValue);
        }
    }
}
